### ISSUE TITLE
trying to compile

### ISSUE THREAD

**Issue by mtweb1** [drkblog/findmacs#2]
js@MICNet:~/findmac$ gcc findmacs.c -o findmacs
findmacs.c: In function ‘main’:
findmacs.c:133:28: warning: too many arguments for format [-Wformat-extra-args]
           fprintf (stderr, "Option -r requires an IP range IP/CIDR.\n", optopt);
                            ^
findmacs.c:135:28: warning: too many arguments for format [-Wformat-extra-args]
           fprintf (stderr, "Option -l requires a filename.\n", optopt);
                            ^
findmacs.c:137:28: warning: too many arguments for format [-Wformat-extra-args]
           fprintf (stderr, "Option -t requires a timeout in milliseconds.\n", optopt);
                            ^

**Comment by drkblog** [comment]
I guess that optopt isn't being used in those and you should remove them.

**Comment by drkblog** [comment]
I changed the file. Try again and let me know.
