### ISSUE TITLE
Undefined Reference Error

### ISSUE THREAD

**Issue by elyeandre** [drkblog/findmacs#4]
Hello,  I tried to compile your code using android-ndk and I got this

[eliot@arch findmacs]$ $CC findmacs.c -o findmacs
/tmp/ccjZFk0I.o:findmacs.c:function getMACs: error: undefined reference to 'hsearch_r'
/tmp/ccjZFk0I.o:findmacs.c:function loadMAClist: error: undefined reference to 'hcreate_r'
/tmp/ccjZFk0I.o:findmacs.c:function loadMAClist: error: undefined reference to 'hsearch_r'
/tmp/ccjZFk0I.o:findmacs.c:function freeMAClist: error: undefined reference to 'hdestroy_r'
collect2: error: ld returned 1 exit status

**Comment by drkblog** [comment]
The linker is failing to find the binary implementation of those functions. IIRC they are in libc. If you compile this with gcc it should work with no extra arguments. What is $CC value?

**Comment by elyeandre** [comment]
I compile it on this way because there's no makefiles 

New method in ndk 12.
$NDK/build/tools/make_standalone_toolchain.py --arch arm --install-dir=/tmp/my-android-toolchain
# Old method.
#$NDK/build/tools/make-standalone-toolchain.sh --platform=android-3 --install-dir=/tmp/my-android-toolchain

# add to terminal PATH variable
export PATH=/tmp/my-android-toolchain/bin:$PATH

# make alias CC be the new gcc binary
export CC=arm-linux-androideabi-gcc

# compile your C code(I tried hello world)
$CC -o foo.o -c foo.c

**Comment by elyeandre** [comment]
can you help me to compile this on android arm?

**Comment by elyeandre** [comment]
![Screenshot_20221104-145317_Termux](https://user-images.githubusercontent.com/96169920/199910241-2f8a3664-6159-4589-b850-4b9c104c999a.jpg)

I finally compiled it. Thanks for your advice
I add -static parameter

**Comment by drkblog** [comment]
You don't need a **Makefile** for this simple script. It still works in Linux arch-x86. I think **android-arm libc** is completely ported as described here: https://android.googlesource.com/platform/bionic/+/8b14256/docs/status.md
I created this branch using the more simple hash search functions because those are ported according to the document. Hopefully this will solve your issue: https://github.com/drkblog/findmacs/tree/android-arm
Let me know if it works.

**Comment by drkblog** [comment]
Oh, I never saw your last message. So it was not including the static library by default. Thank you for the information.
